### ISSUE TITLE
LICENCE file

### ISSUE THREAD

**Issue by piran-e2x** [refractalize/nginx_mod_akamai_g2o#10]
There's no licence file checked-in with the code, and the source code has (c)opyright tags at the top.

Is the source able to be copied? or open source? Is it possible to specify the licence, either here in this issue, or ideally in the code. See https://help.github.com/articles/open-source-licensing/

**Comment by refractalize** [comment]
hi @piran-e2x, this repository has been moved to https://github.com/kaltura/nginx_mod_akamai_g2o, please feel free to resubmit your issue there.

**Comment by piran-e2x** [comment]
Thanks, Will do. But currently the Issue tab is disabled on that repo (attn: @kaltura)

**Comment by refractalize** [comment]
I @erankor, could you open the issues tab on your repository? @piran-e2x would like to raise this...

**Comment by erankor** [comment]
Done. Regarding this specific issue, we normally use AGPL licenses for our projects, @refractalize, are you ok with using this license ?
I'll also need to check with our legal about this, I have no idea what's the policy about projects not originally developed by us...

**Comment by refractalize** [comment]
I have no strong feelings about this. @erankor if you want to go ahead with AGPL then that's fine by me. If that's a problem for anybody then we could resurrect this fork and license it BSD, although they would be falling behind @erankor's more maintained fork.

**Comment by zoharbabin** [comment]
@refractalize and @erankor - are there any 3rd party dependancies to this project (of course aside from NGINX itself)? any libraries it's using or code that was copied from somewhere?

Thanks!

**Comment by erankor** [comment]
Only openssl

**Comment by refractalize** [comment]
code was originally copied from here: http://tool.oschina.net/uploads/apidocs/nginx-zh/HttpAccessKeyModule.htm

Looks like their license was BSD, the same as distributed with Nginx itself. Might not be a bad idea to keep this module under BSD too.

```
/* 
 * Copyright (C) 2002-2015 Igor Sysoev
 * Copyright (C) 2011-2015 Nginx, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */
```

**Comment by piran-e2x** [comment]
Raised an Issue [kaltura/nginx_mod_akamai_g2o#1](https://github.com/kaltura/nginx_mod_akamai_g2o/issues/1), with link back to this Issue.
