### ISSUE TITLE
Suggested improvements

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [refractalize/nginx_mod_akamai_g2o#2]
Hello!

Although I have no doubt, the current version works, several (substantial?) improvements can/should be made. I incorporate all of these in the G2O module for Varnish, which I wrote for my employer and so speak from some experience...
# Multiple nonce-keys.

The process of changing the nonce/password with Akamai is not instantaneous. This is why Akamai are using the nonce concept to begin with -- to allow for multiple (at least -- two) passwords to remain valid in parallel. For some time after you change the Akamai configuration some of their servers will still be using the old nonce, so your back-end (origin) should recognize _both_. I implement this with a simple array of structures -- because the number of valid nonces is small (though greater than 1), linear search through the array is the fastest method :)
# Conversion to string

You are wasting time for each hit converting the computed digest into a character string and then using `strcmp` to compare it with the supplied signature. Instead, it is faster to convert the supplied signature into numbers (of type `uint64_t`) and then comparing the two pairs of numbers:

``` C
    union qdigest {
        unsigned char   bytes[16];
        uint64_t    numbers[2];
    };
    ...
    union qdigest    expected, computed;
    ...
    b64decode(signature, expected.bytes);
    ...
    HMAC_Final(tcontexts + count, computed.bytes, &len);
    ...
    if (len != 16 ||
        expected.numbers[0] != computed.numbers[0] ||
        expected.numbers[1] != computed.numbers[1]) {
        /* Report mismatch */
```
# Recomputing the digest anew

Some of the HMAC computations need only be done once (for each key), yet the current code recomputes the digest anew for each hit. Each thread can keep the HMAC-context for each key and keep reusing it. These two calls need only be done once for each key (in each thread):

``` C
    HMAC_CTX_init(context); /* Is this even necessary? */
    HMAC_Init_ex(context, key, len, EVP_md5(), NULL);
```

After this, for each hit only the following needs to happen:

``` C
    HMAC_Update(context, (const unsigned char *)d, strlen(d));
    HMAC_Update(context, (const unsigned char *)path, strlen(path));
    HMAC_Final(context, computed.bytes, &len);
    HMAC_Init_ex(context, NULL, 0, NULL, NULL);
```

The last call resets the context back to just the key - by passing the zeros, the caller indicates, he wants to reuse the already-supplied key. Presumably, this is faster, than full reinitialization.

I can not (easily) offer a working patch, because I don't have an nginx installation readily available. But you should be able to incorporate (some of) these ideas easily yourself.

**Comment by UnitedMarsupials** [comment]
Actually, we use Varnish in front of Apache -- not nginx. But the decision to implement G2O on the proxy layer was a logical one -- it is Varnish, that Akamai talks to so the checks (if any) should be done there...

I've never used nginx (yet), so I doubt, I'll be able to come up with reasonable patches myself...

**Comment by razvanphp** [comment]
@UnitedMarsupials could you please consider open-sourcing your varnish g2o vmod?

I was just searching for one when I found this nginx mod and decided to use SSL offloading + g2o auth in one step, so traffic between akamai and origin is encrypted (varnish can't to this, as you might know).

I'm not really sure what's the best approach, but since akamai can't provide the edge server IP ranges, people need to use this.
